os: linux
dist: xenial
language: python
python:
  - "3.9"
  - "3.10"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
#script:
#  - wget https://gist.githubusercontent.com/richardtjornhammar/NONE/example0.py && python3 example0.py
